### ISSUE TITLE
world population

### ISSUE THREAD

**Issue by borodadada** [clambin/covid19#128]
Hi! 
https://rapidapi.com/aldair.sr99/api/world-population/
work not correct! fix please!
```
200Success
Body
Headers
{2 items
"ok":true
"body":{2 items
"world_population":6415228245
"total_countries":235
}
}
```

**Comment by clambin** [comment]
can you elaborate on the problem?  any errors you're seeing when loading population?

**Comment by borodadada** [comment]
[clambin](https://github.com/clambin)
world_population = 6415228245

**Comment by clambin** [comment]
eh. think you want to take that up with the provider with that API:  covid19 just consumes that API.  

FYI: covid19 doesn't call the /worldpopulation endpoint, which indeed seems to be underreporting the total population.
